//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDesviaciones.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaInvolucrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AreaInvolucrada()
        {
            this.ResultadoDeAreaInvolucrada = new HashSet<ResultadoDeAreaInvolucrada>();
        }
    
        public int IdAreasInvolucradas { get; set; }
        public string DescripcionAreaInvolucrada { get; set; }
        public bool EstadoAreaInvolucrada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoDeAreaInvolucrada> ResultadoDeAreaInvolucrada { get; set; }
    }
}
