//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDesviaciones.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DesviacionesDBEntities : DbContext
    {
        public DesviacionesDBEntities()
            : base("name=DesviacionesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaInvolucrada> AreaInvolucrada { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Componentes> Componentes { get; set; }
        public virtual DbSet<DocumentosRelacionados> DocumentosRelacionados { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoDesviacion> TipoDesviacion { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Desviaciones> Desviaciones { get; set; }
        public virtual DbSet<ResultadoDeAreaInvolucrada> ResultadoDeAreaInvolucrada { get; set; }
        public virtual DbSet<ResultadoDeDocumentosRelacionados> ResultadoDeDocumentosRelacionados { get; set; }
        public virtual DbSet<ResultadoDePersonalInvolucrado> ResultadoDePersonalInvolucrado { get; set; }
        public virtual DbSet<PersonalInvolucrado> PersonalInvolucrado { get; set; }
    }
}
