//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDesviaciones.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosRelacionados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentosRelacionados()
        {
            this.ResultadoDeDocumentosRelacionados = new HashSet<ResultadoDeDocumentosRelacionados>();
        }
    
        public int IdDocumentosRelacionados { get; set; }
        public string DescripcionDocumentosRelacionados { get; set; }
        public bool EstadoDocumentoRelacionado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoDeDocumentosRelacionados> ResultadoDeDocumentosRelacionados { get; set; }
    }
}
