//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDesviaciones.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInvolucrado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalInvolucrado()
        {
            this.ResultadoDePersonalInvolucrado = new HashSet<ResultadoDePersonalInvolucrado>();
        }
    
        public int IdPersonal { get; set; }
        public string Nombre { get; set; }
        public string Cargo { get; set; }
        public string Apellido { get; set; }
        public string CorreoElectronico { get; set; }
        public bool EstadoPersonal { get; set; }
        public int OrdenAEvaluar { get; set; }
        public string Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoDePersonalInvolucrado> ResultadoDePersonalInvolucrado { get; set; }
    }
}
