//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDesviaciones.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadoDeDocumentosRelacionados
    {
        public int IdDocumento { get; set; }
        public int IdDocumentoRealizado { get; set; }
        public int IdDesviacion { get; set; }
        public bool EstadoDocumento { get; set; }
    
        public virtual Desviaciones Desviaciones { get; set; }
        public virtual DocumentosRelacionados DocumentosRelacionados { get; set; }
    }
}
