//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDesviaciones.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadoDeAreaInvolucrada
    {
        public int IdArea { get; set; }
        public int IdAreasInvolucradas { get; set; }
        public int IdDesviaciones { get; set; }
        public bool EstadoArea { get; set; }
    
        public virtual AreaInvolucrada AreaInvolucrada { get; set; }
        public virtual Desviaciones Desviaciones { get; set; }
    }
}
