//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDesviaciones.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadoDePersonalInvolucrado
    {
        public int IdPersonalInvolucrado { get; set; }
        public int IdPersonal { get; set; }
        public int IdDesviaciones { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public bool EstadoPersonalInvolucrado { get; set; }
    
        public virtual Desviaciones Desviaciones { get; set; }
        public virtual PersonalInvolucrado PersonalInvolucrado { get; set; }
    }
}
